= Pusher Protocol
Pusher Ltd <info@pusher.com>
v7.0, 2014-01-01
:page-layout: base
:page-javascripts: [view-result]
:description: Describes the socket protocol used by clients to communicate with Pusher.
:keywords: pusher, socket, websocket, protocol
:compat-mode!:
:imagesdir: ./images
:includedir: _includes
:toc:
:toc-placement!:
:experimental:
:table-caption!:
:example-caption!:
:figure-caption!:
ifndef::awestruct[]
:idprefix:
:idseparator: -
endif::awestruct[]
:linkattrs:
// URLs
:docs: https://pusher.com/docs

{description}

[NOTE]
====
The protocol documentation is mostly intended for library developers.
Unless you're writing a library, you may wish to consult the server API overview
instead - http://pusher.github.io/pusher-http-api-reference[Pusher HTTP API Reference]
====

Changes to this protocol are handled by incrementing an integer version
number. The current protocol, version 7, is documented here. Currently
protocol 4 and later are supported by Pusher, however clients are encouraged
to keep up to date with changes.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be
interpreted as described in RFC 2119.

toc::[]

== Overview

Clients connect to the pusher service over a given transport.  Once the
connection is established, events are exchanged between both sides.

=== Transports

Pusher supports a number of transports but WebSocket is the default one. The
protocol relies on the fact that WebSocket is message-based.

Once a connection is established with the transport, events start flowing
both ways.

[[events]]
=== Events

Events are JSON-encoded and always occupy a full message in the underlying
transport so that each message can be read and decoded to an event.

Every message is packaged as an 'event', whether it is user-generated, or if
it is a message from the system. There is always an event name that can be
used to determine what should happen to the payload.

[source,json]
----
{
  "event": String,
  "channel": String,
  "data": String
}
----

event (String) ::
  Valid names must be alpha-numerical. The `pusher` prefix is reserved by
  Pusher for protocol expansions.
channel (Maybe String) ::
  Valid names must be alpha-numerical.
  This key may not be used depending on the event name.
data (Maybe String) ::
  Any UTF-8 string.
  This key may not be used depending on the event name.

All events received and sent by clients can contain a `data` field. While all
`pusher`-prefixed events contain only JSON-serializable hashes, it is possible
for publishers to trigger messages containing arbitrarily-encoded data. In
order to keep the protocol consistent, Pusher tries to send the `data` field
as a string. In case of `pusher` events data has to be JSON-serialized first.
For example, Pusher will send:

[source,json]
----
{
  "event": "pusher:connection_established",
  "data": "{\"socket_id\":\"123.456\"}"
}
----

instead of:

[source,json]
----
{
  "event": "pusher:connection_established",
  "data": {"socket_id": "123.456"}
}
----

=== Channels

User events are always sent and received over a channel. And a channel is
defined by it's name.

Channels with the prefix "private-" and "presence-" have different behaviors
as described further below.

== Transports

[[websocket-connection]]
=== WebSocket connection

Clients should make a WebSocket connection to

    [scheme]://ws.pusherapp.com:[port]/app/[key]

scheme ::
  * `ws` - for a normal WebSocket connection
  * `wss` - for a secure WebSocket connection
port ::
  * Default WebSocket ports: 80 (ws) or 443 (wss)
  * For Silverlight clients ports 4502 (ws) and 4503 (wss) may be used.
key ::
  * The app key for the application connecting to Pusher

The following query parameters should be supplied:

protocol (Integer) ::
  The protocol version to use. If this is not supplied the protocol version
  to use is inferred from the version parameter (to support old javascript
  clients which relied on this behaviour). Failing that protocol 1 is used
  (this behaviour is deprecated and will in future be replaced by a 4008
  error code)
client (String) ::
  Identifies the client which is connecting. This string should be of the
  form `platform-library` - for example the iOS library identifies itself as
  `iOS-libPusher`.
version (String) ::
  The version of the library which is connecting, for example `1.9.3`.

For example

    ws://ws.pusherapp.com:80/app/e4d95db9ea1004f66730?client=js&version=2.2&protocol=5

[[websocket-messages]]
=== WebSocket data messages

Data is sent bidirectionally over a WebSocket as text data containing UTF8 encoded JSON.

NOTE: Binary WebSocket frames are not supported.

Every JSON message contains a single **event** and has an `event` property
which is known as the event name. See <<event-types>> below for a description
of the event types.

[[stale-connections]]
=== Detecting that the connection is alive

Both Pusher and clients require a mechanism for establishing that the
connection is alive.

The basic design pattern is described in the
http://www.zeromq.org/deleted:topics:heartbeating[ZeroMQ Wiki] and is
symmetric for the client and Pusher.

Essentially any messages received from the other party are considered to mean
that the connection is alive. In the absence of any messages either party may
check that the other side is responding by sending a ping message, to which
the other party should respond with a pong.

[[ping-pong]]
==== Ping and pong messages

If the WebSocket connection supports ping & pong (i.e. advertises itself as
draft 01 or above), Pusher will send ping messages to the client in order to
verify that it is active.

In recent WebSocket drafts ping & pong are supported as part of the protocol.
Unfortunately this was not the case in earlier drafts, and unfortunately it is
still not possible to trigger sending a ping, or binding to a pong from
JavaScript using the
http://dev.w3.org/html5/websockets/#ping-and-pong-frames[W3C API]. For both
these reasons, Pusher supports both WebSocket protocol level ping-pong and an
emulated one.

In protocol versions 5 and above, when using an old version of the WebSocket
protocol, Pusher will send `pusher:ping` event to the client. The client
should respond with a `pusher:pong` event.

This means that Pusher will respond to a WebSocket protocol ping message
with a pong message, and also it will respond to a `pusher:ping` event with a
`pusher:pong` event (both have empty data).

==== Recommendations for client libraries

If the WebSocket draft supports protocol level ping-pong, then on receipt of a
ping message, the client MUST respond with a pong message.

If the client does not support protocol level pings and advertises (on
connect) that it implements a protocol version >= 5 then the client MUST
respond to a `pusher:ping` event with a `pusher:pong` event.

Clients SHOULD send a ping to Pusher when the connection has been inactive for
some time in order to check that the connection is alive. They MUST then wait
some time for receipt of a pong message before closing the connection /
reconnecting. Clients SHOULD send a protocol ping if supported (sending a
`pusher:ping` event will also work).

Clients MAY use platform specific APIs to trigger a ping check at an
appropriate time (for example when network conditions change).

The precise timeouts before sending a ping and how long to wait for a pong MAY
be configurable by the user of the library, but sensible defaults SHOULD be
specified. The recommended values are:

* Activity timeout before sending ping: 120s
* Time to wait for pong response before closing: 30s

If the client supports protocol version 7, the server will send an
`activity_timeout` value in the data hash of the
`pusher:connection_established` event. The client
SHOULD set the timeout before sending a ping to be the minimum of the value it
has chosen though configuration and the value supplied by the server.

The following example code is taken from the `pusher-js` library. This
function is called whenever a message is received

[source,js]
----
function resetActivityCheck() {
  if (self._activityTimer) { clearTimeout(self._activityTimer); }
  // Send ping after inactivity
  self._activityTimer = setTimeout(function() {
    self.send_event('pusher:ping', {})
    // Wait for pong response
    self._activityTimer = setTimeout(function() {
      self.socket.close();
    }, (self.options.pong_timeout || Pusher.pong_timeout))
  }, (self.options.activity_timeout || Pusher.activity_timeout))
}
----

=== Connection closure

Clients may close the WebSocket connection at any time.

The Pusher server may choose to close the WebSocket connection, in which case
a close code and reason will be sent.

Clients SHOULD support the following 3 ranges

**4000-4099**: The connection SHOULD NOT be re-established unchanged.

**4100-4199**: The connection SHOULD be re-established after backing off. The
  back-off time SHOULD be at least 1 second in duration and MAY be
  exponential in nature on consecutive failures.

**4200-4299**: The connection SHOULD be re-established immediately.

Clients MAY handle specific close codes in particular way, but this is
generally not necessary. See <<error-codes>> below for a list of errors.

NOTE: **Old WebSocket drafts**: If the underlying WebSocket does not support
close codes then a `pusher:error` event will be sent with an appropriate code
before the WebSocket connection is closed.

NOTE: **Legacy protocols**: When using protocol versions < 6, a `pusher:error`
event is also sent before the connection is closed (regardless of the
WebSocket draft).

=== Other transports

The pusher-js library implements a number of fallback transports for older
browsers that don't support WebSocket. This document currently doesn't
describe these transports because we would like to keep them just for the
pusher-js library.

[[event-types]]
== Event types

These are all the events defined by the protocol.

In the docs below "(Pusher -> Client)" indicates that this event is sent from
the Pusher server to to client, and similarly vice versa.

=== `pusher:connection_established` (Pusher -> Client)

After the client has connected to the Pusher service a
`pusher:connection_established` event is triggered. The client must wait for
that event to arrive before issuing any event itself.

[source,json]
----
{
  "event": "pusher:connection_established",
  "data": String
}
----

Where the `data` field is a JSON-encoded hash of following format:

[source,json]
----
{
  "socket_id": String,
  "activity_timeout": Number
}
----

data.socket_id (String) ::
  A unique identifier for the connected client
data.activity_timeout (Number) (Protocol 7 and above) ::
  The number of seconds of server inactivity after which the client should
  initiate a ping message

Within the client libraries the connection is normally established when the
constructor is called.

[source,js]
----
var pusher = new Pusher('APP_KEY');
----

////
@startuml connect.svg
"API User" -> Client: new Pusher("APP KEY")
Client -> Pusher: tcp connect
Pusher -> Client: {"event":"pusher:connection_established",...}
@enduml
////
image::connect.svg[Sequence diagram: connection and connection event]

=== `pusher:error` (Pusher -> Client)

When an error occurs a `pusher:error` event will be triggered. An error may be
sent from Pusher in response to invalid authentication, an invalid command,
etc.

NOTE: **Old WebSocket drafts**: Some errors result in the WebSocket connection
being closed by Pusher. If the WebSocket connection does not support close
codes then a `pusher:error` event will be sent with an appropriate code before
the WebSocket connection is closed.

[source,json]
----
{
  "event": "pusher:error",
  "data": {
    "message": String,
    "code": Integer
  }
}
----

data.message (String) ::
  A textual description of the error
data.code (Integer) - optional ::
  A code that identifies the error that has occurred. See <<error-codes>> below.

[[pusher-ping]]
=== `pusher:ping` (Pusher <--> Client)

When one side wants to verify that the connection is still healty, a
`pusher:ping` event is sent to the other side. See <<ping-pong>>.

[source,json]
----
{
  "event": "pusher:ping"
}
----

[[pusher-pong]]
=== `pusher:pong` (Pusher <--> Client)

Used to reply to a `pusher:ping` event to verify that the connection is still
healty. See <<ping-pong>>.

[source,json]
----
{
  "event": "pusher:pong"
}
----

[[pusher-subscribe]]
=== `pusher:subscribe` (Client -> Pusher)

The `pusher:subscribe` event is generated on the client and sent to Pusher
when a subscription is made. For more information on channel names see the
{docs}/client_api_guide/client_channels[channels documentation].

[source,json]
----
{
  "event": "pusher:subscribe",
  "data": {
    "channel": String,
    "auth": String,
    "channel_data": String
  }
}
----

Where the `data` members are as follows:

data.channel (String) ::
  The name of the channel that is being subscribed to.
data.auth (String) [optional] ::
  If the channel is a presence or private channel then the subscription needs
  to be authenticated. The authentication signature should be provided on
  this property if required. The value will be generated by following the process
  outlined in {docs}/auth_signatures[authentication signatures]. The
  authentication normally takes place on an application server.
data.channel_data (String) [optional] ::
  This property should be populated with additional information about the channel
  if the channel is a presence channel. The JSON for the `channel_data` will be
  generated on the application server and should be encoded as a string and
  assigned to this property. The format of the object is as follows:

.Example JSON
[source,json]
----
{
  "event": "pusher:subscribe",
  "data": {
    "channel": "presence-example-channel",
    "auth": "<APP_KEY>:<server_generated_signature>",
    "channel_data": "{
      \"user_id\": \"<unique_user_id>\",
      \"user_info\": {
        \"name\": \"Phil Leggetter\",
        \"twitter\": \"@leggetter\",
        \"blogUrl\":\"http://blog.pusher.com\"
      }
    }"
  }
}
----

For more information see {docs}/authenticating_users[authenticating users].

From the API users point of view the subscription is made the moment that the
`subscribe` method is called. However, the actual moment within the client
library that a `pusher:subscribe` event is triggered depends on the type of
channel that is being subscribed to.

[source,js]
----
var pusher = new Pusher('APP_KEY');
var channel = pusher.subscribe('public-channel');
----

==== Public channel subscription

Since no authentication must take place when subscribing to a public channel
the `pusher:subscribe` event can be sent from the client to Pusher as soon as
the call to `subscribe` is made.

////
@startuml subscribe.svg
"API User" -> "Client Library": pusher.subscribe("public-channel")
"Client Library" -> Pusher: {"event":"pusher:subscribe","data":"...public-channel..."}
@enduml
////
image::subscribe.svg[Sequence diagram: subscribing to a public channel]

==== Private and Presence channel subscription

Private and Presence channels require authentication so an additional call
needs to be made to the application server hosting the web application in
order to make sure the current user can subscribe to the given channel.

////
@startuml subscribe-private.svg
"API User" -> "Client Library": pusher.subscribe("private-channel")
"Client Library" -> "App Server": /pusher/auth/?channel_name=private-channel&\nsocket_id=<socket id>
"App Server" --> "Client Library": <auth response>
"Client Library" -> Pusher: {"event":"pusher:subscribe","data":"{\"channel\"\:...}"}
@enduml
////
image::subscribe-private.svg[Sequence diagram: subscribing to a private channel]

For more information on authentication of channels see the
{docs}/authenticating_users[Authenticating Users docs].

=== `pusher_internal:subscription_succeeded` (Pusher -> Client)

The `pusher_internal:subscription_succeeded` event is sent when a subscription
to a channel is successful.

[source,json]
----
{
  "event": "pusher_internal:subscription_succeeded",
  "channel": "example-channel",
  "data": String
}
----

Where the `data` field is empty except for presence channels.

.Presence data
[source,json]
----
{
  "presence": {
    "ids": Array,
    "hash": Hash,
    "count": Integer,
  }
}
----

channel (String) ::
  The presence channel name
data.presence.ids (Array) ::
  An array of unique user identifiers who are subscribe to the channel.
data.presence.hash (Hash) ::
  A hash of user IDs to object literals containing information about that user.
data.presence.count (Integer) ::
  The number of users subscribed to the presence channel

.Example JSON
[source,json]
----
{
  "event": "pusher_internal:subscription_succeeded",
  "channel": "presence-example-channel",
  "data": "{
    \"presence\": {
    \"ids\": [\"11814b369700141b222a3f3791cec2d9\",\"71dd6a29da2a4833336d2a964becf820\"],
    \"hash\": {
      \"11814b369700141b222a3f3791cec2d9\": {
        \"name\":\"Phil Leggetter\",
        \"twitter\": \"@leggetter\"
      },
      \"71dd6a29da2a4833336d2a964becf820\": {
        \"name\":\"Max Williams\",
        \"twitter\": \"@maxthelion\"
      }
    },
    \"count\": 2
  }"
}
----


=== `pusher:unsubscribe` (Client -> Pusher)

The `pusher:unsubscribe` event is generated on the client and sent to Pusher
when a client wishes to unsubscribe from a channel.

[source,json]
----
{
  "event": "pusher:unsubscribe",
  "data" : String
}
----

Where the `data` field is a JSON-encoded hash of following format:

[source,json]
----
{
  "channel": String
}
----

data.channel (String) ::
  The name of the channel to be unsubscribed from.

Unsubscribing works in the same way as subscribing to a channel with the only
difference being that the event name is `pusher:unsubscribe`.

[source,js]
----
var pusher = new Pusher('APP_KEY');
var channel = pusher.subscribe('public-channel');

// ...

pusher.unsubscribe('my-channel');
----

////
@startuml unsubscribe.svg
"API User" -> "Client Library": pusher.unsubscribe('public-channel')
"Client Library" -> Pusher: {"event": "pusher:unsubscribe", "data": "...public-channel..."}
@enduml
////
image::unsubscribe.svg[Sequence diagram: unsubscribing]

=== `pusher_internal:member_added` (Pusher -> Client)

When a user subscribes to a presence channel the
`pusher_internal:member_added` is triggered on the channel by Pusher.

[source,json]
----
{
  "event": "pusher_internal:member_added",
  "channel": "presence-example-channel",
  "data": String
}
----

Where the `data` field is a JSON-encoded hash of following format:

[source,json]
----
{
  "user_id": String,
  "user_info": Object
}
----

channel (String) ::
  The presence channel name
data.user_id (String) ::
  The ID of a user who has just subscribed to the presence channel.
data.user_info (Object) ::
  An object containing information about that user who has just subscribed
  to the channel. The contents of the `user_info` property depends on what
  the application server replied with when the presence channel was
  authenticated.

.Example JSON
[source,json]
----
{
  "event": "pusher_internal:member_added",
  "channel": "presence-example-channel",
  "data": "{
    \"user_id\": \"11814b369700141b222a3f3791cec2d9\",
    \"user_info\": {
      \"name\": \"Phil Leggetter\",
      \"twitter\": \"@leggetter\",
      \"blogUrl\": \"http://blog.pusher.com\"
    }
  }"
}
----

For more about the `user_info` object literal see `user_info` in the
{docs}/authenticating_users[authenticating users] section.

=== `pusher_internal:member_removed` (Pusher -> Client)

When a user unsubscribes from a presence channel by either actually
unsubscribing or their transport connection closing the
`pusher_internal:member_removed` is triggered on the channel by Pusher. The
different event name is used to differentiate a public event from an internal
one.

[source,json]
----
{
  "event": "pusher_internal:member_removed",
  "channel": "presence-example-channel",
  "data": String
}
----

Where the `data` field is a JSON-encoded hash of following format:

[source,json]
----
{
  "user_id": String
}
----

channel (String) ::
  The presence channel name
data.user_id (String) ::
  The ID of a user who has just unsubscribed from the presence channel.


[[channel-events]]
=== User events (Pusher -> Client)

User events are user defined and associated with a single channel.

[source,json]
----
{
  "event": String,
  "channel": String,
  "data": String
}
----

event (String) ::
  The name of the event
channel (String) ::
  The name of the channel that the event is associated with e.g. `test-channel`
data (String) ::
  The data associated with the event. It is strongly recommended that this be
  a JSON-serialized hash (e.g. `{"hello":"world", "foo": {"bar": 1000}}`),
  although it is possible to send any type of payload, for example a simple
  string.

NOTE: The following code shows how to receive an event and not how to trigger
one

[source,js]
----
var pusher = new Pusher('APP_KEY');
var channel = pusher.subscribe('my-channel');
channel.bind('my-event', function(data){
  // handle event
});
----

////
@startuml receive-events.svg
Server -> Pusher: Trigger:\n channel=my-channel\n event=my-event\n data={"hello":"world"}
Pusher -> Client: {"channel": "my-channel", "event": "my-event", "data": "{\"hello\":\"world\"}"}
@enduml
////
image::receive-events.svg[Sequence diagram: Receiving events]

[[channel-client-events]]
=== User events (Client -> Pusher)

It is possible to trigger events from a client when the application that the
client has connected to has had client events enabled, the event name must be
prefixed with `client-` and the channel must be an authenticated channel
(private or presence).

Pusher will send client events to all other clients that are subscribed to the
private or presence channel. Pusher will not send it to the originator of the event.

For more information see
{docs}/client_api_guide/client_events#trigger-events[Triggering Client Events
docs].

[source,json]
----
{
  "event": String,
  "channel": String,
  "data": String/Object
}
----

event (String) ::
  The name of the event which must be prefixed with `client-` to be accepted.
  For example, `client-event` or `client-something-updated`
channel (String) ::
  The channel for the event to be triggered on. To be accepted the channel
  must be either a private (`private-`) or a presence (`presence-`) channel.
data (String/Object) ::
  The data to be sent and associated with the event. It is strongly
  recommended that this be a hash of key/value pairs
  (`{"hello":"world", "foo": {"bar": 1000}}`) although it is possible to
  send any type of payload, for example a simple string.

[source,js]
----
var pusher = new Pusher('APP_KEY');
var channel = pusher.subscribe('private-channel');
var data = {"some": "data"};
channel.trigger("client-event", data);
----

////
@startuml client-event.svg
"API User" -> "Client Library": channel.trigger('client-event',\n {"some":"data"})
"Client Library" -> Pusher: {"event:"client-event",\n "channel":"private-channel",\n "data":"{\"some\":\"data\"}"}
note right: Pusher then distributes to\nall other clients subscribed\nto the channel.
@enduml
////
image::client-event.svg[Sequence diagram: triggering a client event]

[[error-codes]]
## Error Codes

=== 4000-4099

Indicates an error resulting in the connection being closed by Pusher, and
that attempting to reconnect using the same parameters will not succeed.

4000:: Application only accepts SSL connections, reconnect using wss://

4001:: Application does not exist

4003:: Application disabled

4004:: Application is over connection quota

4005:: Path not found

4006:: Invalid version string format

4007:: Unsupported protocol version

4008:: No protocol version supplied

=== 4100-4199

Indicates an error resulting in the connection being closed by Pusher, and
that the client may reconnect after 1s or more.

4100:: Over capacity

=== 4200-4299

Indicates an error resulting in the connection being closed by Pusher, and
that the client may reconnect immediately.

4200::
  Generic reconnect immediately
4201::
  Pong reply not received: ping was sent to the client, but no reply was
  received - see <<ping-pong>>
4202::
  Closed after inactivity: Client has been inactive for a long time
  (currently 24 hours) and client does not support ping. Please upgrade to a
  newer WebSocket draft or implement version 5 or above of this protocol.

=== 4300-4399

Any other type of error.

4301:: Client event rejected due to rate limit

[[changelog]]
## CHANGELOG

=== Version 7 (2013-11)

The server now sends the activity timeout in the
`pusher:connection_established` event.

=== Version 6 (2013-03)

When the server closes connections due to an error, a `pusher:error` event is
only sent if and old WebSocket draft is in use which does not support close
codes. Clients SHOULD therefore expose the close code and reason in some way
to the developer.

=== Version 5 (2012-01)

Pusher expects the client to respond to ping messages See <<ping-pong>>

=== Version 4 (2011-12)

Added a confirmation message after subscribing to public and private channels
(already sent for presence channels)

=== Version 3 (2011-02)

Significant change to presence events.

=== Version 2

Renamed `connection_established` event to `pusher:connection_established`

=== Version 1

Initial release
